cargo-features = ["per-package-target"]

[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
forced-target = "x86_64-unknown-none"

[dependencies]
bootloader_api = "0.11.7"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
